version: '3.8'
services:
  influxdb:
    image: 'quay.io/influxdb/influxdb:2.0.0-rc'
    container_name: influxdb
    networks:
      - iot_default
    ports:
      - '8086:8086'
    volumes:
      - ////c/vm/iot/influxdb:/root/.influxdbv2
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - iot_default
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    restart: unless-stopped
networks:
  iot_default:
    external: true
